name: kubectl-setup
description: Install and configure kubectl for AKS

inputs:
  access-token: 
    description: A valid PAT with suitable permissions
    required: true

  azure-credentials:
    description: Azure Credentials
    required: true

  resource-group:
    description: Azure Resource Group
    required: true

runs:
  using: "composite"
  steps:
    - name: install kubectl
      uses:  azure/setup-kubectl@v5
      with:
        version: 'latest'

    - name: azure login
      uses: azure/login@v3
      with:
        creds: '${{ inputs.azure-credentials }}'

    - name: install kubelogin
      uses: azure/use-kubelogin@v1.3
      env:
        GITHUB_TOKEN: '${{ inputs.access-token }}'
      with:
        kubelogin-version: 'latest'

    - name: set kubectl context
      uses: azure/aks-set-context@v5
      with:
        resource-group: '${{ inputs.resource-group }}'
        cluster-name: '${{ inputs.resource-group }}-kubernetes'

    - name: convert kubeconfig for kubelogin
      shell: bash
      run: kubelogin convert-kubeconfig -l azurecli
