name: kubectl-apply-file-yaml
description: Applies the Kubectl Yaml  file

inputs:
  namespace:
    description: The namespace to deploy the Yaml
    default: "default"
    required: false

  file-name:
    description: The yaml to apply
    required: true
    
  replace-yaml:
    description: Whether to use kubectl replace or not
    required: false
    type: boolean
  
  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps:
    - name: Apply the Yaml to the cluster
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if ${{ inputs.replace-yaml }}
          kubectl replace -n "${{ inputs.namespace }}" -f ${{ inputs.file-name }}
        else
          kubectl apply -n "${{ inputs.namespace }}" -f ${{ inputs.file-name }}
        fi
