version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    groups:
      github-actions:
        patterns: ["*"]
