name: 'dotnet-build-pack-push - engage'

on:
  workflow_call:
    inputs:
      nuget-packages:
        description: 'List of Nuget packages to create'
        required: true
        type: string
      npm-packages:
        description: 'List of NPM packages to create'
        required: true
        type: string
      run-number:
        description: 'The workflow run number.'
        required: true
        type: string
      run-attempt:
        description: 'The workflow run-attempt number.'
        required: true
        type: string
      repository-owner:
        description: 'The owner of the repository from which this flow was invoked'
        required: true
        type: string
    secrets:
      access-token:
        description: 'The personal Access token passed from the calling flow'
        required: true
      azure-feed-access-token:
        description: 'The personal access token for Azure feed when installing the n3o tool'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          source-url: https://pkgs.dev.azure.com/n3oltd/_packaging/Feed/nuget/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.azure-feed-access-token }}

      - name: Setup Node
        if: inputs.npm-packages != ''
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - name: n3o tool install and prepack
        uses: n3o/actions/.github/actions/n3o-install-prepack@main
        with:
          azure-feed-pat: ${{ secrets.azure-feed-access-token }}

      - name: dotnet build
        uses: n3o/actions/.github/actions/dotnet-build@main

      - name: dotnet pack all projects
        uses: n3o/actions/.github/actions/dotnet-pack@main
        with:
          projects: ${{ inputs.nuget-packages }}

      - name: dotnet push all nuget packages
        uses: n3o/actions/.github/actions/dotnet-push@main
        with:
          projects: ${{ inputs.nuget-packages }}
          repository-owner: ${{ inputs.repository-owner }}
          access-token: ${{ secrets.access-token }}

      - name: npm publish clients packages
        if: inputs.npm-packages != ''
        uses: n3o/actions/.github/actions/npm-publish@main
        with:
          client-directories: ${{ inputs.npm-packages }}
          repository-owner: ${{ inputs.repository-owner }}
          access-token: ${{ secrets.access-token }} 
          
        

      

      
