name: n3o-cli install
description: Installs the n3o-cli tool

inputs:
  access-token:
    description: access token for the nuget source
    required: true
  azure-client-id:
    description: Azure client id for key vault access
    required: true
  azure-client-secret:
    description: Azure client secret for key vault access
    required: true
  azure-tenant-id:
    description: Azure tenant id for key vault access
    required: true

runs:
  using: "composite"
  steps:
    - name: dotnet tool install n3o
      env:
        AZURE_CLIENT_ID: ${{ inputs.azure-client-id }}
        AZURE_CLIENT_SECRET: ${{ inputs.azure-client-secret }}
        AZURE_TENANT_ID: ${{ inputs.azure-tenant-id }}
      shell: bash
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/n3oltd/index.json --name n3oltd --username n3oltd --password ${{ inputs.access-token }} --store-password-in-clear-text
        dotnet tool install --global --no-cache n3o
        echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"
        {
          echo "AZURE_CLIENT_ID=${{ inputs.azure-client-id }}"
          echo "AZURE_CLIENT_SECRET=${{ inputs.azure-client-secret }}"
          echo "AZURE_TENANT_ID=${{ inputs.azure-tenant-id }}"
        } >> "$GITHUB_ENV"
