name: n3o-cli install
description: Installs the n3o-cli tool

inputs:
  access-token:
    description: access token for the nuget source
    required: true

runs:
  using: "composite"
  steps:
    - name: dotnet tool install n3o
      shell: bash
      run: |
        dotnet new tool-manifest
        dotnet tool install --no-cache n3o --add-source https://nuget.pkg.github.com/n3oltd/index.json --username n3oltd --password ${{ inputs.access-token }}
