name: Trigger Platforms JS Deployment (QA)
description: Triggers the Platforms JS deployment to QA

inputs:    
  workflows-token:
    description: GitHub token (required to run gh commands)
    required: true

runs:
  using: "composite"
  steps:
    - name: run
      shell: bash
      run: |
        gh workflow run platforms-js-qa-deployment.yml --repo n3oltd/deployments
      env:
        GH_TOKEN: ${{ inputs.workflows-token }}