name: n3o install
description: Installs the n3o dotnet tool

inputs:
  working-directory:
    description: Working Directory
    required: true

  access-token:
    description: access token for the nuget source
    required: true

runs:
  using: "composite"
  steps:
    - name: Add Github source credentials to nuget.config
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        dotnet nuget update source n3oltd -u n3oltd -p ${{inputs.access-token}} --store-password-in-clear-text

    - name: dotnet tool install n3o
      shell: bash
      run: |
        dotnet new tool-manifest
        dotnet tool install --no-cache n3o 
