name: kubectl-apply-files
description: Use kubectl to apply the specified YAML files

inputs:
  namespace:
    description: The namespace to pass to kubectl
    required: false

  working-directory:
    description: The directory where the YAML files are located
    required: true

runs:
  using: "composite"
  steps:
    - name: apply-yaml
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -n "${{ inputs.namespace }}" ]; then
          find . -maxdepth 1 -name '*.yaml' ! -name 'postgresSecrets.yaml' -exec kubectl apply -f {} -n "${{ inputs.namespace }}" \;
        else
          find . -maxdepth 1 -name '*.yaml' ! -name 'postgresSecrets.yaml' -exec kubectl apply -f {} \;
        fi
