name: dotnet-restore-build
description: Restore and build

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
  
  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps:
    - name: add Github Source Credentials to nuget.config
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        dotnet nuget update source n3oltd -u n3oltd -p ${{inputs.access-token}} --store-password-in-clear-text
        dotnet nuget list source
      
    - name: dotnet restore
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: dotnet restore --no-cache -v m

    - name: dotnet build
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        version=$(date +"%Y.%m.%d")-${{ github.run_number }}
        echo "Version: $version"
        dotnet build --no-restore -c Release /property:Version=$version
