name: dotnet-restore-build
description: Restore and build

runs:
  using: "composite"
  steps:
    - name: dotnet restore
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: dotnet restore --no-cache -v m

    - name: dotnet build
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        version=$(date +"%Y.%m.%d")-${{ github.run_number }}
        echo "Version: $version"
        dotnet build --no-restore -c Release /property:Version=$version