name: dotnet-restore-build
description: Restore and build

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
    
  build-configuration:
    description: The build configuration to run
    default: Release
  
  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps:
    - name: add Github Source Credentials to nuget.config
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        dotnet nuget update source n3oltd -u n3oltd -p ${{inputs.access-token}} --store-password-in-clear-text

    - name: dotnet build
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        dotnet build -c "${{inputs.build-configuration}}" 
