name: dotnet-restore-build
description: Restore and build

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
    
  build-configuration:
    description: The build configuration to run
    default: Release
  
  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps:
    - name: dotnet build
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      env:
        GH_USERNAME: n3oltd
        GH_PAT: ${{ inputs.access-token }}
        NUGET_CERT_REVOCATION_MODE: offline
      run: |
        dotnet build -c "${{inputs.build-configuration}}" 
