name: Trigger Build Service Container
description: Triggers the container build for the service

inputs:
  repo-name:
    description: the name of the repository 
    required: true
    
  workflows-token:
    description: GitHub token (required to run gh commands)
    required: true

runs:
  using: "composite"
  steps:
    - name: run build-container workflow
      shell: bash
      run: |
        gh workflow run build-container.yml --repo n3oltd/${{ inputs.repo-name }}
      env:
        GH_TOKEN: ${{ inputs.workflows-token }}