name: npm-publish-react
description: Publishes the react app to github packages

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
      
  working-directory:
    description: The working directory
    default: ''
    
runs:
  using: "composite"
  steps:
    - name: npm publish
      shell: bash
      run: |
        (cd ${{ inputs.working-directory }}; 
        version=$(date +"%Y.%m.%d")-${{ github.run_number }};
        npm version $version;)      
        cat .npmrc        
        npm publish ${{ inputs.working-directory }};      