name: npm-publish-react
description: Publishes the react app to github packages

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
      
  working-directory:
    description: The working directory
    default: ''

runs:
  using: "composite"
  steps:
    - name: npm publish
      shell: bash
      run: |
        version=$(date +"%Y.%-m.%-d")-${{ github.run_number }}
        ls -a
        echo $version
        echo "Print working directory: $PWD"
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.access-token }}" >> .npmrc
        echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc
        cat .npmrc
        ls -a
        npm version $version      
        npm publish
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      env:
        NODE_AUTH_TOKEN: ${{inputs.access-token}}