name: npm-publish-react
description: Publishes the react app to github packages

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true
      
  working-directory:
    description: The working directory
    default: ''
    
runs:
  using: "composite"
  steps:
    - name: npm publish
      shell: bash
      run: |
        version=$(date +"%Y.%m.%d")-${{ github.run_number }}
        ls -a
        echo $version        
        echo "Print working directory: $PWD"
        (cd ${{ inputs.working-directory }};
        npm version $version;
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.access-token }}" >> .npmrc;
        echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc;
        cat .npmrc;
        npm publish)
      working-directory: ${{github.workspace}}
      env:
        NODE_AUTH_TOKEN: ${{inputs.access-token}} 