name: dotnet-push
description: Push NuGet packages to a private feed

inputs:
  projects:
    description: The list of projects to pack as a JSON array
    required: true

  access-token: 
    description: A valid PAT with suitable permissions
    required: true

runs:
  using: "composite"
  steps:
    - name: dotnet push
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        projects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        for project in $projects
        do
          echo "Project: $project"
          (cd $project; dotnet nuget push **/*.nupkg -k ${{inputs.access-token}} --source "https://nuget.pkg.github.com/n3oltd/index.json" --skip-duplicate)
        done

    - name: Push Nuget packages to Azure Artifacts
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        listOfProjects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')        
        for project in $listOfProjects
        do
          echo "Pushing project: $project"          
          (cd $project; dotnet nuget push **/*.nupkg --skip-duplicate --api-key az --source n3o )          
        done   