name: dotnet-push
description: Push NuGet packages to a private feed

inputs:
  access-token: 
    description: A valid PAT with suitable permissions
    required: true

  projects:
    description: The list of projects to pack as a JSON array
    required: true

  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps:
    - name: dotnet push
      shell: bash
      working-directory: ${{github.workspace}}/${{ inputs.working-directory }}
      run: |
        projects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        for project in $projects
        do
          echo "Project: $project"
          $csProj = find . -path "\*$project.nupkg"
          (dotnet nuget push "$csProj" -k ${{inputs.access-token}} --source "https://nuget.pkg.github.com/n3oltd/index.json" --skip-duplicate)
        done    
