name: dotnet-push
description: "Pushing the Dotnet packages to Github Packages"

inputs:  
  projects:
    description: 'The json array list of projects'
    required: true
  repository-owner: 
    description: 'Owner username of the repository that run the main-ci.yaml'    
    required: true
  access-token: 
    description: 'The personal Access token passed from the calling flow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Push Nuget Package to GitHub packages feed
      shell: bash
      working-directory: ${{github.workspace}}/src
      run: |
        listOfProjects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        echo $listOfProjects        
        for project in $listOfProjects
        do
          echo "Pushing project: $project"
          echo $PWD
          (cd $project; dotnet nuget push **/*.nupkg -k ${{inputs.access-token}} --source "https://nuget.pkg.github.com/${{ inputs.repository-owner }}/index.json" --skip-duplicate )          
        done                 
      
      