name: dotnet-pack
description: Create NuGet packages

inputs:
  projects:
    description: The list of projects to pack as a JSON array
    required: true

  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps: 
    - name: dotnet-pack
      shell: bash
      run: |
        version=$(date +"%Y.%m.%d").${{ github.run_number }}
        projects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        for project in $projects
        do
          echo "Packing: $project"
          dotnet pack --configuration Release "${{ inputs.working-directory }}/$project/$project.csproj" /p:PackageVersion=$version 
        done
