name: dotnet-pack
description: Create NuGet packages

inputs:
  build-configuration:
    description: The build configuration to run
    default: Release

  version-suffix:
    description: The Suffix to add to the package version
    default: ''
  
  projects:
    description: The list of projects to pack as a JSON array
    required: true

  working-directory:
    description: "The working directory"
    default: src

runs:
  using: "composite"
  steps: 
    - name: dotnet-pack
      shell: bash
      run: |
        version=$(date +"%Y.%m.%d").${{ github.run_number }}
        if [ "${{ inputs.version-suffix }}" != "" ];then
          version=$version-${{ inputs.version-suffix }}
        fi
        projects=$(echo '${{ inputs.projects }}' | jq -c -r '.[]')
        for project in $projects
        do
          echo "Packing: $project"
          csProj=$(find . -path \*$project/$project.csproj)
          dotnet pack --configuration "${{inputs.build-configuration}}" "$csProj" /p:PackageVersion=$version 
        done
