name: n3o-build-apk
description: Builds the apk of the app

inputs:
  working-directory:
    description: "The working directory"
    default: android

  app-identifier:
    description: "package-name"
    required: false

  android-keystore-base64:
    description: "The keystore in base64"
    required: true

  android-keystore-password:
    description: "The android keystore password"
    required: true

  android-key-alias:
    description: "The android key alias"
    required: true

  android-key-password:
    description: "The android key password"
    required: true

  google-play-key-base64:
    description: "The json key for Google Play in base64"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21"
        cache: "gradle"

    - name: Decode key files
      shell: bash
      run: |
        echo "${{ inputs.android-keystore-base64 }}" | base64 -d > fastlane/release-key.keystore
        echo '${{ inputs.google-play-key-base64 }}' | base64 -d > fastlane/service-account.json
      working-directory: ${{ inputs.working-directory }}

    - name: Build & upload the APK to internal track
      shell: bash
      run: bundle exec fastlane internal
      env:
        KEYSTORE_PASSWORD: ${{ inputs.android-keystore-password }}
        KEY_ALIAS: ${{ inputs.android-key-alias }}
        KEY_PASSWORD: ${{ inputs.android-key-password }}
        APP_IDENTIFIER: ${{ inputs.app-identifier }}
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      working-directory: ${{ inputs.working-directory }}
