name: n3o-build-apk
description: Builds the apk of the app

inputs:
  working-directory:
    description: "The working directory"
    default: src
    
  android-keystore-base64:
    description: "The keystore in base64"
    required: true

  google-play-key-base64:
    description: "The json key for Google Play in base64"
    required: true

  app-identifier:
    description: "package-name"
    required: false 

  android-key-alias:
    description: "The android key alias"
    required: true
    
  android-keystore-password:
    description: "The android keystore password"
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "21"
        cache: "gradle"

    - name: Setup ruby and fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"

    - name: Decode key files
      shell: bash
      run: |
        echo "${{ inputs.android-keystore-base64 }}" | base64 -d > android/fastlane/release-key.keystore
        echo '${{ inputs.google-play-key-base64 }}' | base64 -d > android/fastlane/service-account.json
      working-directory: ${{ inputs.working-directory }}

    - name: Build & upload APK to internal track
      shell: bash
      run: |
        bundle install
        bundle exec fastlane internal
      env:
        KEYSTORE_PASSWORD: ${{ inputs.android-keystore-password }}
        KEY_ALIAS: ${{ inputs.android-key-alias }}
        KEY_PASSWORD: ${{ inputs.android-keystore-password }}
        APP_IDENTIFIER: ${{ inputs.app-identifier }} 
      working-directory: ${{ inputs.working-directory }}

