name: kubectl-apply-yaml
description: Use kubectl to apply the specified YAML

inputs:
  namespace:
    description: The namespace to pass to kubectl
    required: false

  yaml:
    description: The YAML to apply
    required: true

runs:
  using: "composite"
  steps:
    - name: apply-yaml
      shell: bash
      env:
        YAML_CONTENTS: ${{ inputs.yaml }}      
      run: |
        echo "$YAML_CONTENTS" > contents.yml
        kubectl apply -n "${{ inputs.namespace }}" -f contents.yml
