name: kubectl-apply-yaml
description: Applies the Kubectl Yaml

inputs:
  namespace:
    description: The namespace to deploy the Yaml
    required: false

  yaml:
    description: The yaml to apply
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply the Yaml to the cluster
      shell: bash
      env:
        YAML_CONTENTS: ${{ inputs.yaml }}      
      run: |
        if [[ -n "${{ inputs.namespace }}" ]]; then
          echo "$YAML_CONTENTS" | kubectl apply -n "${{ inputs.namespace }}" -f -
        else
          echo "$YAML_CONTENTS" | kubectl apply -f -
        fi