name: kubectl-apply-yaml
description: Applies the Kubectl YAML

inputs:
  namespace:
    description: The namespace to deploy the Yaml
    required: false

  yaml:
    description: The yaml to apply
    required: true
    
  replace-yaml:
    description: Whether to use kubectl replace or not
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Apply the Yaml to the cluster
      shell: bash
      env:
        YAML_CONTENTS: ${{ inputs.yaml }}      
      run: |        
        echo "$YAML_CONTENTS" > secrets.yml
        
        if ${{ inputs.replace-yaml }}; then
          echo "Running kubectl replace..."
          kubectl replace -n "${{ inputs.namespace }}" -f secrets.yml
        else
          echo "Running kubectl apply..."
          kubectl apply -n "${{ inputs.namespace }}" -f secrets.yml
        fi
