name: npm-publish
description: Publishes one or more npm packages

inputs:
  access-token:
    description: A valid PAT with suitable permissions
    required: true

  azure-feed-token:
    description: An Azure feeds token
    required: true

  package-directories:
    description: The list of package directories as a JSON array
    required: true

runs:
  using: "composite"
  steps:
    - name: npm publish
      shell: bash
      run: |
        version=$(date +"%Y.%m.%d")-${{ github.run_number }}
        packageDirectories=$(echo '${{ inputs.package-directories }}' | jq -c -r '.[]')
        for packageDirectory in $packageDirectories
        do
          (cd $packageDirectory; npm version $version; echo "//npm.pkg.github.com/:_authToken=${{ inputs.access-token }}" >> .npmrc; echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc; ls -a; npm publish)
        done
      working-directory: ${{github.workspace}}
      env: 
        NODE_AUTH_TOKEN: ${{inputs.access-token}}
        
    - name: Npm publish to Azure feed
      shell: bash
      run: |
        listOfDirectories=$(echo '${{ inputs.client-directories }}' | jq -c -r '.[]')                
        for packageDirectory in $listOfDirectories        
        do          
          ( cd $packageDirectory; rm .npmrc; 
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:username=a2658dbf-ef4b-4609-9d8d-9c65c96f86a4" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:_password=${{ inputs.azure-feed-token }}" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/:email=n3oltd@n3oltd.com" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:username=n3oltd" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:_password=${{ inputs.azure-feed-token }}" >> .npmrc;
            echo "//pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/:email=n3oltd@n3oltd.com" >> .npmrc; 
            echo "@n3oltd:registry=https://pkgs.dev.azure.com/n3oltd/_packaging/Feed/npm/registry/" >> .npmrc;
            cat .npmrc; ls -a; npm publish )
        done
      working-directory: ${{github.workspace}}