name: kubectl-apply
description: Applies the Kubectl commands

inputs:
  namespace:
    description: The namespace to deploy the files within
    required: false

  working-directory:
    description: The directory where the YAML files are located
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply the YAML files
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        kubectl apply -n ${{ inputs.namespace }} -f '*.yaml'
