name: n3o-tool prepack
description: Prepares projects for packaging

runs:
  using: "composite"
  steps: 
    - name: n3o prepack
      shell: bash
      run: n3o-tool prepack --verbose -p ${{github.workspace}}/src     