name: Auto add issue to specified project

on:
  workflow_call:
    inputs:
      project-number:
        type: string
        required: true

jobs:
  add-issue-to-specified-project:
    name: Add issue to specified project
    runs-on: ubuntu-latest
    steps:
      - name: Assign to Specified Project
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: 'https://github.com/orgs/n3oltd/projects/${{ inputs.project-number }}'
          github-token: ${{ secrets.AUTOMATION_WORFLOWS_TOKEN }}