name: 'dotnet-build-pack-push-myget'

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest

      dotnet-version:
        type: string
        default: 8.x

      working-directory:
        type: string
        default: src

      build-configuration:
        type: string
        default: Release

jobs:
  myGet:
    name: MyGet
    
    runs-on: ${{ inputs.runs-on }}
    
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - id: prepare
        name: Set version
        run: |
          NOW=$(date +'%Y.%-m.%-d')
          VERSION="$NOW.${{ github.run_number }}"   
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --configuration ${{ inputs.build-configuration }} --no-restore /property:Version=${{ steps.prepare.outputs.VERSION }}

      - name: dotnet pack
        run: dotnet pack --configuration ${{ inputs.build-configuration }} /property:Version=${{ steps.prepare.outputs.VERSION }}

      - name: dotnet nuget push
        run: dotnet nuget push "**/*.nupkg" --source "https://www.myget.org/F/n3o-umbraco/api/v2/package" --api-key "${{ secrets.MYGET_API_KEY }}" --skip-duplicate
