name: 'Deploy Mobile App'

on:
  workflow_call:
    inputs:
      app-id:
        type: string
        required: true
      
      environment-id:
        type: string
        required: true

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  deploy-platforms:
    name: Deploy Mobile App
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            mobile-apps/${{ inputs.app-id }}/${{ inputs.environment-id }}
            
      - id: latest-json-metadata
        name: Read latest JSON metadata
        working-directory:  mobile-apps/${{ inputs.app-id }}/${{ inputs.environment-id }}/latest
        run: |
          bundleName=$(jq -r '.bundleName' metadata.json)
          echo "bundleName=bundleName" >> $GITHUB_OUTPUT
      
      - name: Set Capgo channel
        run:
          npx @capgo/cli@latest channel set ${{ inputs.environment-id }} ${{ inputs.app-id }} --bundle ${{ steps.step_id.outputs.bundleName }} --apikey=${{ secrets.CAPGO_API_KEY_UPLOAD }}
          