name: 'Build & Deploy Platforms Playground'

on:
  workflow_call:

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ env.GH_PAT }}      

      - name: npm install and build
        run: |
          npm install --legacy-peer-deps
          npx turbo build --filter=@n3oltd/platforms-playground
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}
          VITE_SUBSCRIPTION_CODE: ${{ inputs.subscription-code }}
          VITE_ENVIRONMENT: ${{ inputs.environment }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Storage Connection String
        run: |
          echo "storage_connection_string=${{ secrets.AZURE_STORAGE_ELEMENTS_CONNECTION_STRING_PROD }}" >> $GITHUB_ENV          

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.66.0
          inlineScript: |
            az storage blob delete-batch --connection-string "${{ env.storage_connection_string }}" --source "platforms-playground"  --pattern "js/*" 
            az storage blob upload-batch --connection-string="${{ env.storage_connection_string }}" --destination="platforms-playground" --source="apps/platforms-playground/dist" --destination-path="js" --overwrite="true"        
