name: dotnet build

on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: dotnet build
        uses: n3o/actions/.github/actions/dotnet-restore-build@main
