name: 'dotnet build'

on:
  workflow_call:
    inputs:
      build-configuration:
        type: string
        description: The build configuration to run
        default: Release
      
      working-directory:
        type: string
        default: src

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: dotnet build
        uses: n3oltd/actions/.github/actions/dotnet-restore-build@main
        with:
          access-token: ${{ env.GH_PAT }}
          build-configuration: ${{ inputs.build-configuration }}
          working-directory: ${{ inputs.working-directory }}
          