name: 'Deploy N3O services to AKS'

on:
  workflow_call:
    inputs:
      data-region:
        type: string
        required: true
        
      namespace:
        type: string
        required: true

      service-id:
        type: string
        required: true

jobs:
  deploy-to-aks:
    name: Deploy service to AKS

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.data-region }}/${{ inputs.namespace }}

      - id: latest-json-metadata
        name: Read latest JSON metadata
        working-directory: ${{ inputs.data-region }}/${{ inputs.namespace }}/${{ inputs.service-id }}/latest
        run: |
          deploymentVersion=$(jq -r '.deploymentVersion' metadata.json)
          echo "deploymentVersion=$deploymentVersion" >> $GITHUB_OUTPUT
          
      - name: Install and configure kubectl with AKS
        uses: n3oltd/actions/.github/actions/n3o-kubectl-setup@main
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ inputs.data-region }}

      - name: Apply YAML files to cluster
        uses: n3oltd/actions/.github/actions/n3o-kubectl-apply-files@main
        with:
          namespace: ${{ inputs.namespace }}
          working-directory: ${{ inputs.data-region }}/${{ inputs.namespace }}/${{ inputs.service-id }}/${{ steps.latest-json-metadata.outputs.deploymentVersion }}
