name: dotnet build, pack and push

on:
  workflow_call:
    inputs:
      npm-packages:
        description: List of npm package directories as a JSON array
        required: true
        type: string

      nuget-packages:
        description: List of NuGet packages to create as a JSON array
        required: true
        type: string

      working-directory:
        type: string
        default: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: setup-node
        if: inputs.npm-packages != ''
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - name: n3o tool install
        uses: n3oltd/actions/.github/actions/n3o-tool-install@main

      - name: n3o tool prepack
        uses: n3oltd/actions/.github/actions/n3o-tool-prepack@main

      - name: dotnet build
        uses: n3oltd/actions/.github/actions/dotnet-restore-build@main
        with:
          access-token: ${{ secrets.GH_PACKAGES_TOKEN }}
          working-directory: ${{ inputs.working-directory }}

      - name: dotnet pack
        uses: n3oltd/actions/.github/actions/dotnet-pack@main
        with:
          projects: ${{ inputs.nuget-packages }}
          working-directory: ${{ inputs.working-directory }}

      - name: dotnet push
        uses: n3oltd/actions/.github/actions/dotnet-push@main
        with:
          access-token: ${{ secrets.GH_PACKAGES_TOKEN }}
          projects: ${{ inputs.nuget-packages }}
          working-directory: ${{ inputs.working-directory }}

      - name: npm publish clients packages
        if: inputs.npm-packages != ''
        uses: n3oltd/actions/.github/actions/npm-publish@main
        with:
          package-directories: ${{ inputs.npm-packages }}
          access-token: ${{ secrets.GH_PACKAGES_TOKEN }}
          azure-feed-token: ${{ secrets.AZURE_FEED_CREDENTIALS }} 