name: 'Build & Push Platforms App APK'

on:
  workflow_call:
    inputs:
      subscription-code:
        type: string
        required: true
        
jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      #- name: Fetch assets (config + images)
      #        uses: wei/wget@v1
      # with:
      #   args: -O apps/platforms-app/assets/zip https://cdn.n3o.cloud/connect-${{ inputs.subscription-code }}/assets/zip

      #- name: Process assets
      #  run: |
      #    #extract 
      #    #use values from config file
      #    #npx capacitor-assets generate
      
      - name: npm install and build
        run: |
          npm clean-install
          npm run build          
          
      - name: sync capacitor plugins
        run: |
          npx cap sync
        working-directory: apps/platforms-app
        
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"          

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.keystore
        working-directory: apps/platforms-app
        
      - name: Create Signing Config
        run: |
          echo "
          android {
              signingConfigs {
                  release {
                      storeFile file('my-release-key.keystore')
                      storePassword '${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
                      keyAlias '${{ secrets.ANDROID_KEY_ALIAS }}'
                      keyPassword '${{ secrets.ANDROID_KEYSTORE_PASSWORD }}'
                  }
              }
              buildTypes {
                  release {
                      signingConfig signingConfigs.release
                  }
              }
          }
          " >> android/app/build.gradle
        working-directory: apps/platforms-app

      - name: Build APK        
        run: ./gradlew assembleRelease --no-daemon
        working-directory: apps/platforms-app/android

      #this can be replaced with fastlane
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: capacitor-apk
          path: apps/platforms-app/android/app/build/outputs/apk/release/app-*.apk