name: 'dotnet-upgrade-nuget-build-commit'

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: src
      
      repos:
        description: List of services to process
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          
      - name: install n3o cli
        uses: n3oltd/actions/.github/actions/n3o-cli-install@main
        with:
          access-token: ${{ secrets.GH_PACKAGES_TOKEN }}
      
      - name: update-nuget-packages
        env:
          GH_TOKEN: ${{ secrets.GH_REPO_PACKAGES_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_PACKAGES_NUGET_USERNAME }}
          GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          git config --global url."https://x-access-token:${GH_PAT}@github.com/".insteadOf "https://github.com/"

          services=$(echo '${{ inputs.repos }}' | jq -c -r '.[]')

          for service in $services; do
            echo "Processing $service..."

            mkdir -p "$service"
            git clone "https://github.com/n3oltd/$service.git" "$service"

            (
              cd "$service/src"
              git config user.name "N3O Bot"
              git config user.email "no-reply@n3o.ltd"
              
              dotnet tool run n3o nuget upgrade-our-packages

              if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit -m "Upgraded NuGet packages"
                git push origin main
              else
                echo "No package updates found for $service"
              fi
            )
          done
