name: 'docker-build-push-postgres'

on:
  workflow_call:

jobs:
  build-push-docker-image-job:    

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
                            
      - id: buildx
        uses: docker/setup-buildx-action@v1

      - name: acr login
        uses: docker/login-action@v1
        with:
          registry: n3oltd.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: fetch dockerfile
        uses: wei/wget@v1
        with:
          args: -O postgres https://raw.githubusercontent.com/n3oltd/actions/main/docker/postgres

      - id: meta-postgres
        name: prepare postgres
        run: |
          DOCKER_IMAGE_NAME=n3o-postgres
          DOCKER_IMAGE=n3oltd.azurecr.io/$DOCKER_IMAGE_NAME
          NOW=$(date +'%Y.%-m.%-d')
          VERSION="$NOW.${{ github.run_number }}"       
          VERSIONTAG="${DOCKER_IMAGE}:${VERSION}"
          LATESTTAG="${DOCKER_IMAGE}:latest"
          echo "versiontag=$VERSIONTAG" >> $GITHUB_OUTPUT
          echo "latesttag=$LATESTTAG" >> $GITHUB_OUTPUT

      - name: build and push postgres
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          target: final
          file: postgres
          push: true
          tags: ${{ steps.meta-webserver.outputs.versiontag }} , ${{ steps.meta-webserver.outputs.latesttag }}
