name: 'Build Platforms App APK'

on:
  workflow_call:
    inputs:
      subscription-code:
        type: string
        required: true
        
env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}
  
jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch configuration.json
        run: |
          wget -O configuration.json "https://cdn.n3o.cloud/connect-${{ inputs.subscription-code }}/build/configuration.json"

      - name: Download assets
        run: |
          asset=$(jq -r '.theme.mobileApp | to_entries[] | .value' configuration.json)
          for url in $urls; do
            fname=$(basename "${url%%\?*}")   # strip query params
            wget -O "apps/platforms-app/assets/$fname" "$url"
          done
          
      - name: Set environment variables
        id: setenv
        run: |
          APP_NAME=$(jq -r '.app.appName' configuration.json)
          PACKAGE_NAME=$(jq -r '.app.packageName' configuration.json)
          VERSION_NAME=$(date +"%Y.%m.%d")-${{ github.run_number }}
          CI_BUILD_NUMBER=${{ github.run_number }}
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "CI_BUILD_NUMBER=$CI_BUILD_NUMBER" >> $GITHUB_ENV
      
      - name: npm install and build
        run: |
          npm clean-install
          npm run build    
          
      - name: Sync capacitor plugins
        run: |
          npx trapeze run config.yml -y
          npx cap sync
          npx capacitor-assets generate
        working-directory: apps/platforms-app
        
      - name: Build Android APK
        uses: n3oltd/actions/.github/actions/n3o-build-apk@main
        with:
          working-directory: apps/platforms-app
          android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          android-key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: platforms-app-${{ inputs.subscription-code }}
          path: apps/platforms-app/android/app/build/outputs/apk/release/app-*.apk