name: 'docker-build-push-qa'

on:
  workflow_call:
    inputs:
      docker-file:
        type: string
        required: true

      project:
        type: string
        required: true
      
      projectId:
        type: string
        required: true
      
      projectName:
        type: string
        required: true

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  job1:
    name: build and push docker image 

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with:
          ref: github-migration

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - name: acr login
        uses: docker/login-action@v1
        with:
          registry: n3oltd.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: fetch dockerfile
        uses: wei/wget@v1
        with:
          args: -O ${{ inputs.docker-file }} https://raw.githubusercontent.com/n3oltd/actions/main/docker/${{ inputs.docker-file }}

      - id: meta-webserver
        name: prepare web server
        run: |
          DOCKER_IMAGE_NAME=$(echo ${{ inputs.project }} | tr '[:upper:]' '[:lower:]' | tr "." "-")
          DOCKER_IMAGE=n3oltd.azurecr.io/$DOCKER_IMAGE_NAME
          NOW=$(date +'%Y.%-m.%-d')
          VERSION="$NOW.${{ github.run_number }}"
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=tags::${TAGS}

      - name: build and push web server
        uses: docker/build-push-action@v2        
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./src
          target: final
          file: ${{ inputs.docker-file }}
          build-args: |
            PROJECT=${{inputs.project}}
            FEED_URL="https://nuget.pkg.github.com/n3oltd/index.json"
            PAT=${{ env.GH_PAT }}
          push: true
          tags: ${{ steps.meta-webserver.outputs.tags }}          