name: 'dotnet-build-webserver'

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: src

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build-webserver:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: setting the npmrc file
        run: |
          rm .npmrc
          echo "unsafe-perm=true" >> .npmrc
          echo "package-lock=false" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ env.GH_PAT }}" >> .npmrc
          echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
        working-directory: ${{ inputs.working-directory }}/K2.WebServer          

      - name: dotnet build
        uses: n3oltd/actions/.github/actions/dotnet-restore-build@main
        with:
          access-token: ${{ env.GH_PAT }}
          working-directory: ${{ inputs.working-directory }}