name: n3o nightly build container

on:
  workflow_call:
    inputs:
      repo-name:
        type: string
        default: src
        required: true

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: trigger build service container workflow
        uses: n3oltd/actions/.github/actions/n3o-trigger-build-service-container@main
        with:
          repo-name: ${{ inputs.service-id }}
          workflows-token: ${{ secrets.AUTOMATION_WORFLOWS_TOKEN }}