name: n3o auto-triage new issue

on:
  workflow_call:
    inputs:
      label:
        description: Label to apply when a new issue is opened with no labels.
        type: string
        default: 'status/needs-triage'

jobs:
  mark:
    if: github.event.issue.labels[0] == null
    runs-on: ubuntu-latest

    steps:
      - name: apply triage label
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh issue edit ${{ github.event.issue.number }} \
            --repo ${{ github.repository }} \
            --add-label "${{ inputs.label }}"
