name: Deploy Platforms Pages

on:
  workflow_call:
    inputs:
      data-region:
        type: string
        required: true
      
      site-id:
        type: string
        required: true

jobs:
  deploy-to-aks:
    name: Deploy to AKS

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.data-region }}/sites/${{ inputs.site-id }}
            
      - id: get-deployment-version
        name: Get Deployment Version
        working-directory: ${{ inputs.data-region }}/sites/${{ inputs.site-id }}/latest
        run: |
          deploymentVersion=$(jq -r '.deploymentVersion' metadata.json)
          echo "deploymentVersion=$deploymentVersion" >> $GITHUB_OUTPUT
          
      - name: kubectl Setup
        uses: n3oltd/actions/.github/actions/n3o-kubectl-setup@main
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ inputs.data-region }}
          
      - name: Apply YAML
        uses: n3oltd/actions/.github/actions/n3o-kubectl-apply-files@main
        with:
          working-directory: ${{ inputs.data-region }}/sites/${{ inputs.site-id }}/${{ steps.get-deployment-version.outputs.deploymentVersion }}
          replace-yaml: false
