name: Trim Github Packages 

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-type:
        required: true
        type: string

jobs:
  delete-old-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.package-name }}
          package-type: ${{ inputs.package-type }}
          min-versions-to-keep: 90
          token: ${{ secrets.GH_PACKAGES_DELETE_TOKEN }}
