name: 'Build & Deploy Link Builder'

on:
  workflow_call:

env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ env.GH_PAT }}

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.66.0
          inlineScript: |
            az storage blob upload -f "build/link-builder.js" --connection-string="${{ env.storage_connection_string }}" --container-name="elements" --content-type="text/javascript" --overwrite="true"
        env:
          storage_connection_string: "${{ secrets.AZURE_STORAGE_ELEMENTS_CONNECTION_STRING }}"
