name: Publish NPM package to GitHub Packages

on:
  workflow_call:
    inputs:
      version-suffix:
        type: string
        description: The Suffix to add to the package version
        required: false
        default: ''

      working-directory:
        type: string
        default: src
        
env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          token: ${{ env.GH_PAT }}

      - name: npm install and build
        run: |
          npm install
          npm run build

      - run: |     
          cp README.md dist/README.md
          cp package.json dist/package.json
          npm config set registry https://npm.pkg.github.com

      - run: |
          version=$(date +"%Y.%m.%d")-${{ github.run_number }}        
          echo "//npm.pkg.github.com/:_authToken=${{ env.GH_PAT }}" >> .npmrc
          echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc
          if [ "${{ inputs.version-suffix }}" != "" ];then
            npm version $version --preid=${{ inputs.version-suffix }}
          else
            npm version $version;
          fi
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}