name: 'npm-publish'

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
        
      version:
        type: string
        required: true
        
      prepack:
        type: boolean
        default: false

    secrets:
      npm-token:
        required: true
    
jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
          
      - if: ${{ inputs.prepack }}
        run: |
          npm run prepack
          
      - if: ${{ inputs.prepack }}
        run: |
          cp ../LICENSE.md dist/LICENSE.md
          cp README.md dist/README.md
          jq 'del(.devDependencies) | del(.scripts) | del(.dependencies) | .main = \"index.js\"' package.json > dist/package.json
      
      - run: |
          packageVersion="$(echo "${{ inputs.version }}" | sed 's/\(.*\)\./\1-/')"
          cd dist
          echo $PACKAGE_JSON > package.json
          npm version $packageVersion
          cat package.json
          npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
          PACKAGE_JSON: ${{ steps.prepare.outputs.value }}
