name: 'npm-publish'

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
        
      version:
        type: string
        required: true
        
      prepack:
        type: boolean
        default: false

    secrets:
      npm-token:
        required: true
    
jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          
          
      - if: ${{ inputs.prepack }}
        run: |
          npm run prepack
          
      - if: ${{ inputs.prepack }}
        run: |
          dir=$(pwd -P)
          while [ -n "$dir" -a ! -f "$dir/LICENSE.md" ]; do
              dir=${dir%/*}
          done
          if [ -f "$dir/LICENSE.md" ]; then cp "$dir/LICENSE.md" dist/LICENSE.md; fi
          cp README.md dist/README.md
          jq "del(.devDependencies) | del(.scripts) | del(.dependencies) | .main = \"index.js\"" package.json > dist/package.json
          cd dist
          
      - run: |
          packageVersion="$(echo "${{ inputs.version }}" | sed 's/\(.*\)\./\1-/')"
          npm version $packageVersion
          npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
