name: link builder publish

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true

      version:
        type: string
        required: true

      prepack:
        type: boolean
        default: false
        
env:
  GH_PAT: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory != '' && inputs.working-directory || '.' }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - run: |     
          cp README.md dist/README.md
          cp package.json dist/package.json

      - run: |          
          cd dist
          echo "//npm.pkg.github.com/:_authToken=${{ env.GH_PAT }}" >> .npmrc
          echo "@n3oltd:registry=https://npm.pkg.github.com" >> .npmrc    
          cat .npmrc
          pwd
          packageVersion="$(echo "${{ inputs.version }}" | sed 's/v\(.*\)/\1/')"
          npm version $packageVersion --git-tag-version false
          npm publish --userconfig .npmrc --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}