name: link builder publish

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true

      version:
        type: string
        required: true

      prepack:
        type: boolean
        default: false

jobs:
  build-publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory != '' && inputs.working-directory || '.' }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - run: |
          if [ -f "$dir/LICENSE.md" ]; then cp "$dir/LICENSE.md" build/LICENSE.md; fi
          mkdir build/umd
          cp build/n3o-attribution.umd.cjs build/umd/n3o-attribution.umd.cjs
          cp build/n3o-attribution.umd.cjs.gz build/umd/n3o-attribution.umd.cjs.gz
          cp README.md build/README.md
          jq "del(.devDependencies) | del(.scripts) | del(.dependencies) | .main = \"n3o-attributions.js\" | .files = ["umd/n3o-attribution.umd.cjs", "umd/n3o-attribution.umd.cjs.gz"]" package.json > build/package.json          
          cd build

      - run: |
          packageVersion="$(echo "${{ inputs.version }}" | sed 's/v\(.*\)/\1/')"
          npm version $packageVersion --git-tag-version false
          npm publish --tag latest --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}