name: 'oauth-static-site-deploy'

on:
  workflow_call:
    inputs:
      client-id:
        type: string
        required: true

      docker-image:
        type: string
        required: true

      email-domains:
        type: string
        required: true

      resource-group:
        type: string
        required: true

      site-name:
        type: string
        required: true

      tenant-id:
        type: string
        required: true

    secrets:
      azure-credentials:
        required: true

      client-secret:
        required: true

      cookie-secret:
        required: true
    
jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config container set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --docker-custom-image-name ${{ env.custom_image }} --docker-registry-server-url https://n3oltd.azurecr.io
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_CLIENT_ID="${{ env.client_id }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_CLIENT_SECRET="${{ env.client_secret }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_COOKIE_SECRET="${{ env.cookie_secret }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_EMAIL_DOMAINS="${{ env.email_domains }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_PROVIDER="azure"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_AZURE_TENANT_ID="${{ env.tenant_id }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OAUTH2_PROXY_OIDC_ISSUER_URL="https://sts.windows.net/${{ env.tenant_id }}/"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings WEBSITES_PORT="8080"
            az webapp restart --name ${{ env.app_name }} --resource-group ${{ env.resource_group }}
        env:
          app_name: "${{ inputs.site-name }}"
          client_id: "${{ inputs.client-id }}"
          client_secret: "${{ secrets.client-secret }}"
          cookie_secret: "${{ secrets.cookie-secret }}"
          custom_image: "n3oltd.azurecr.io/${{ inputs.docker-image }}:latest"
          email_domains: "${{ inputs.email-domains }}"
          resource_group: "${{ inputs.resource-group }}"
          tenant_id: "${{ inputs.tenant-id }}"
          
