name: test-secrets-decode

on:
  workflow_dispatch:

jobs:
  decode-secret:
    name: Decode Secret

    runs-on: ubuntu-latest

    steps:
      - name: decode secret
        shell: bash
        env:
          YAML_CONTENTS: ${{ secrets.EU1_POSTGRES_2024_10_25_2 }}
        run: |
          # Save the content to a file
          echo "$YAML_CONTENTS" > secret.yaml
          
          # Verify the content by displaying it (it may be masked in the log if it matches the secret pattern)
          cat secret.yaml