name: test-secrets-decode

on:
  workflow_call:

jobs:
  decode-secret:
    name: Decode Secret

    runs-on: ubuntu-latest

    steps:
      - name: decode secret
        shell: bash
        env:
          YAML_CONTENTS: ${{ secrets.EU1_POSTGRES_2024_10_25_2 }}
        run: |
          # Decode the Base64 content (assuming it’s Base64 encoded)
          echo "$YAML_CONTENTS" | base64 -d | cat