name: 'umbraco-deploy'

on:
  workflow_call:
    inputs:
      docker-image:
        type: string
        required: true

      resource-group:
        type: string
        required: true

      environment-id:
        type: string
        required: true

      site-name:
        type: string
        required: true

      storage-container:
        type: string
        default: 'umbraco'

      localization-date-format:
        type: string
        default: dmy_slashes

      localization-language:
        type: string
        default: en

      localization-number-format:
        type: string
        default: international

      localization-time-format:
        type: string
        default: '24'

      localization-timezone:
        type: string
        default: 'Etc/UTC'

      site-language-tag:
        type: string
        required: true

      site-name-tag:
        type: string
        required: true
        
      sentry-dsn:
        type: string
        default: "none"
        
      sentry-send-default-pii:
        type: string
        default: true
        
      sentry-max-request-body-size:
        type: boolean
        default: true
        
      sentry-minimum-breadcrumb-level:
        type: string
        default: "Debug"
        
      sentry-minimum-event-level:
        type: string
        default: "Warning"
        
      sentry-attach-stack-trace:
        type: boolean
        default: true
        
      sentry-debug:
        type: boolean
        default: true
        
      sentry-diagnostic-level:
        type: string
        default: Error
    
    
    
    secrets:
      azure-credentials:
        required: true

      db-connection-string:
        required: true

      db-engage-connection-string:
        required: false

      storage-connection-string:
        required: false

jobs:
  job1:
    name: ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config container set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --docker-custom-image-name ${{ env.custom_image }} --docker-registry-server-url https://n3oltd.azurecr.io
            az webapp config connection-string set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings umbracoDbDSN="${{ env.db_connection_string }}" --connection-string-type SQLAzure
            az webapp config connection-string set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings umbracoDbDSN_ProviderName="Microsoft.Data.SqlClient" --connection-string-type SQLAzure
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings ASPNETCORE_ENVIRONMENT="${{ env.aspnetcore_environment }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings ASPNETCORE_FORWARDEDHEADERS_ENABLED="true" 
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_DateFormat="${{ env.date_format }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_Language="${{ env.language }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_NumberFormat="${{ env.number_format }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_TimeFormat="${{ env.time_format }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_Timezone="${{ env.timezone }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_SiteLanguageTag="${{ env.site_language_tag }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings N3O_SiteNameTag="${{ env.site_name_tag }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings UMBRACO__STORAGE__AZUREBLOB__MEDIA__CONTAINERNAME="${{ env.storage_container }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings UMBRACO__STORAGE__AZUREBLOB__MEDIA__CONNECTIONSTRING="${{ env.storage_connection_string }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings OPENSSL_FORCE_FIPS_MODE="0"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__Dsn="${{ env.sentry-dsn }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__SendDefaultPii="${{ env.sentry_send_default_pii }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__MaxRequestBodySize="${{ env.sentry_max_request_body_size }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__MinimumBreadcrumbLevel="${{ env.sentry_minimum_breadcrumb_level }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__MinimumEventLevel="${{ env.sentry_minimum_event_level }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__AttachStackTrace="${{ env.sentry_attach_stack_trace }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__Debug="${{ env.sentry_debug }}"
            az webapp config appsettings set --name ${{ env.app_name }} --resource-group ${{ env.resource_group }} --settings Sentry__DiagnosticLevel="${{ env.sentry_diagnostic_level }}"
            az webapp restart --name ${{ env.app_name }} --resource-group ${{ env.resource_group }}
            
            if [[ -n "$db_engage_connection_string" ]]; then
              az webapp config connection-string set --name "$app_name" --resource-group "$resource_group" --settings umbracoEngageDbDSN="$db_engage_connection_string" --connection-string-type SQLServer
            fi
        env:
          app_name: "${{ inputs.site-name }}"
          custom_image: "n3oltd.azurecr.io/${{ inputs.docker-image }}:latest"
          db_connection_string: "${{ secrets.db-connection-string }}"
          db_engage_connection_string: "${{ secrets.db-engage-connection-string }}"
          aspnetcore_environment: "${{ inputs.environment-id }}"
          date_format: "${{ inputs.localization-date-format }}"
          language: "${{ inputs.localization-language }}"
          number_format: "${{ inputs.localization-number-format }}"
          resource_group: "${{ inputs.resource-group }}"
          time_format: "${{ inputs.localization-time-format }}"
          timezone: "${{ inputs.localization-timezone }}"
          site_language_tag: "${{ inputs.site-language-tag }}"
          site_name_tag: "${{ inputs.site-name-tag }}"
          storage_container: "${{ inputs.storage-container }}"
          storage_connection_string: "${{ secrets.storage-connection-string }}"
          sentry_dsn: "${{ inputs.sentry-dsn }}"
          sentry_send_default_pii: "${{ inputs.sentry-send-default-pii}}"
          sentry_max_request_body_size: "${{ inputs.sentry-max-request-body-size}}"
          sentry_minimum_breadcrumb_level: "${{ inputs.sentry-minimum-breadcrumb-level}}"
          sentry_minimum_event_level: "${{ inputs.sentry-minimum-event-level}}"
          sentry_attach_stack_trace: "${{ inputs.sentry-attach-stack-trace}}"
          sentry_debug: "${{ inputs.sentry-debug}}"
          sentry_diagnostic_level: "${{ inputs.sentry-diagnostic-level}}"